---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# shinyGames

<!-- badges: start -->
<!-- badges: end -->

In this package we use [T-rex Runner] (https://github.com/wayou/t-rex-runner) Game. It has two variants - `corona` and `dinosaur`.

## Installation

You can install the released version of shinyGames from GitHub with:

``` r
# install.packages("remotes")
remotes::install_github("deepanshu88/shinyGames")
```

## Example

This is a basic example which shows you how to run game:

```{r example, eval=FALSE}
library(shiny)
library(shinyGames)
ui <- fluidPage( game(type = "corona") )
server <- function(input, output, session) { }
shinyApp(ui, server)
```

## Toggle between corona and dinosaur games

```{r example2, eval=FALSE}
library(shiny)
library(shinyGames)

ui <- fluidPage(

  selectizeInput("gameid", "Select Game",
                        choices = c("corona", "dino"),
                        options = list(
                       placeholder = 'Please select an option below',
                       onInitialize = I('function() { this.setValue(""); }')
                     )),
  uiOutput("myout")

  )

server <- function(input, output, session) {

  output$myout <- renderUI({

    if(nchar(input$gameid) > 0) {
      game(type = input$gameid)
    }

  })

}

shinyApp(ui, server)

```

